definitions:
  dto.Instruction:
    properties:
      step:
        type: string
    type: object
  dto.Recipe:
    properties:
      categories:
        items:
          type: string
        type: array
      cook_time:
        type: integer
      description:
        type: string
      image_url:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          $ref: '#/definitions/dto.Instruction'
        type: array
      prep_time:
        type: integer
      servings:
        type: integer
      title:
        type: string
    type: object
  models.Category:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.Ingredient:
    properties:
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
    type: object
  models.Instruction:
    properties:
      id:
        type: string
      recipeID:
        type: string
      stepNumber:
        type: integer
      stepText:
        type: string
    type: object
  models.Recipe:
    properties:
      categories:
        items:
          $ref: '#/definitions/models.Category'
        type: array
      cook_time:
        type: integer
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      ingredients:
        items:
          $ref: '#/definitions/models.Ingredient'
        type: array
      instructions:
        items:
          $ref: '#/definitions/models.Instruction'
        type: array
      prep_time:
        type: integer
      servings:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /recipe:
    get:
      consumes:
      - application/json
      description: Get all Recipes
      operationId: get-all-recipes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Recipe'
            type: array
      summary: Get All Recipes
      tags:
      - Recipe
    post:
      consumes:
      - application/json
      description: Add a Recipe
      operationId: add-recipes
      parameters:
      - description: Recipe Data
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/dto.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Recipe'
      summary: Add a Recipe
      tags:
      - Recipe
swagger: "2.0"
